# Class: postfix::server
#
# The title is used for the 'myhostname' parameter.
#
# When setting 'postgrey' to true, you might want to install a custom
# file as /etc/postfix/postgrey_whitelist_clients.local too.
#
# Sample Usage :
#
class postfix::server (
  # To install postfix-mysql package instead of plain postfix (EL5)
  $mysql = false,
  # See the main.cf comments for help on these options
  $myhostname = $::fqdn,
  $mydomain = false,
  $myorigin = '$myhostname',
  $inet_interfaces = 'localhost',
  $inet_protocols = 'all',
  $master_service_disable = false,
  $proxy_interfaces = false,
  $mydestination = '$myhostname, localhost.$mydomain, localhost',
  $local_recipient_maps = false,
  $luser_relay = false,
  $unknown_local_recipient_reject_code = '550',
  $mynetworks_style = false,
  $mynetworks = false,
  $relay_domains = false,
  $relayhost = false,
  $relay_recipient_maps = false,
  $transport_maps = false,
  $in_flow_delay = '1s',
  $alias_maps = 'hash:/etc/aliases',
  $alias_database = 'hash:/etc/aliases',
  $recipient_delimiter = false,
  $home_mailbox = false,
  $mail_spool_directory = false,
  $mailbox_command = false,
  $smtpd_banner = '$myhostname ESMTP $mail_name',
  $setgid_group = $::postfix::params::setgid_group,
  $mailbox_size_limit = undef,
  $message_size_limit = false,
  $mail_name = false,
  $virtual_alias_domains = false,
  $virtual_alias_maps = false,
  $virtual_mailbox_domains = false,
  $virtual_mailbox_maps = false,
  $virtual_mailbox_base = false,
  $virtual_uid_maps = false,
  $virtual_gid_maps = false,
  $virtual_transport = false,
  $dovecot_destination = '${recipient}',
  $masquerade_classes = false,
  $masquerade_domains = false,
  $smtpd_helo_required = false,
  $smtpd_client_restrictions = [],
  $smtpd_helo_restrictions = [],
  $smtpd_sender_restrictions = [],
  $smtpd_recipient_restrictions = [],
  $smtpd_data_restrictions = [],
  $smtpd_end_of_data_restrictions = [],
  $smtpd_delay_reject = false,
  $ssl = false,
  $smtpd_tls_key_file = undef,
  $smtpd_tls_cert_file = undef,
  $smtpd_tls_CAfile = undef,
  $smtpd_sasl_auth = false,
  $smtpd_sasl_type = 'dovecot',
  $smtpd_sasl_path = 'private/auth',
  $smtp_sasl_auth = false,
  $smtp_sasl_password_maps = undef,
  $smtp_sasl_security_options = undef,
  $smtp_tls_CAfile = undef,
  $smtp_tls_CApath = undef,
  $smtp_tls_key_file = undef,
  $smtp_tls_cert_file = undef,
  $smtp_tls_security_level = undef,
  $smtp_tls_secure_cert_match = undef,
  $smtp_tls_note_starttls_offer = false,
  $smtp_tls_mandatory_ciphers = undef,
  $smtpd_tls_ask_ccert = false,
  $tls_append_default_CA = false,
  $smtp_sasl_tls = false,
  $smtp_use_tls = false,
  $canonical_maps = false,
  $sender_canonical_maps = false,
  $smtp_generic_maps = false,
  $relocated_maps = false,
  $extra_main_parameters = {},
  # master.cf
  $smtp_content_filter = [],
  $smtps_content_filter = [],
  $submission = false,
  # EL5
  $submission_smtpd_enforce_tls = 'yes',
  # EL6
  $submission_smtpd_tls_security_level = 'encrypt',
  $submission_smtpd_sasl_auth_enable = 'yes',
  $smtps_smtpd_sasl_auth_enable = 'yes',
  # submission should only be used for authenticated delivery, so explicitly
  # reject everything else.
  $submission_smtpd_client_restrictions = 'permit_sasl_authenticated,reject',
  # smtps should allow unauthenticated delivery (for local or relay_domains for
  # example) so no explicit reject. smtps port 465 is non-standards compliant 
  # anyway so no one true answer. 
  $smtps_smtpd_client_restrictions = 'permit_sasl_authenticated',
  $master_services = [],
  # Other files
  $header_checks = [],
  $body_checks = [],
  # Postscreen - available in Postfix 2.8 and later
  $postscreen                  = false,
  $postscreen_access_list      = ['permit_mynetworks'],
  $postscreen_blacklist_action = 'enforce',
  $postscreen_cache_map        = 'btree:$data_directory/postscreen_cache',
  $postscreen_greet_wait       = '${stress?2}${stress:6}s',
  $postscreen_greet_banner     = '$smtpd_banner',
  $postscreen_greet_action     = 'enforce',
  $postscreen_dnsbl_sites      = [],
  $postscreen_dnsbl_reply_map  = undef,
  $postscreen_dnsbl_threshold  = 1,
  $postscreen_dnsbl_action     = 'enforce',
  # Spamassassin
  $spamassassin        = false,
  $sa_required_hits    = '5',
  $sa_report_safe      = '0',
  $sa_rewrite_header   = [],
  $sa_trusted_networks = '10/8 172.16/12 192.168/16',
  $sa_skip_rbl_checks  = '1',
  $sa_loadplugin       = [ 'Mail::SpamAssassin::Plugin::SPF' ],
  $sa_score            = [ 'FH_DATE_PAST_20XX 0' ],
  $spampd_port         = '10026',
  $spampd_relayport    = '10027',
  $spampd_children     = '20',
  $spampd_maxsize      = '512',
  # Other filters
  $postgrey                = false,
  $postgrey_policy_service = undef,
  $clamav                  = false,
  # Parameters
  $command_directory      = $::postfix::params::command_directory,
  $config_directory       = $::postfix::params::config_directory,
  $daemon_directory       = $::postfix::params::daemon_directory,
  $data_directory         = $::postfix::params::data_directory,
  $manpage_directory      = $::postfix::params::manpage_directory,
  $readme_directory       = $::postfix::params::readme_directory,
  $sample_directory       = $::postfix::params::sample_directory,
  $postfix_package        = $::postfix::params::postfix_package,
  $postfix_mysql_package  = $::postfix::params::postfix_mysql_package,
  $postfix_package_ensure = $::postfix::params::postfix_package_ensure,
  $postgrey_package       = $::postfix::params::postgrey_package,
  $service_restart        = $::postfix::params::service_restart,
  $spamassassin_package   = $::postfix::params::spamassassin_package,
  $spampd_package         = $::postfix::params::spampd_package,
  $spampd_config          = $::postfix::params::spampd_config,
  $spampd_template        = $::postfix::params::spampd_template,
  $root_group             = $::postfix::params::root_group,
  $mailq_path             = $::postfix::params::mailq_path,
  $newaliases_path        = $::postfix::params::newaliases_path,
  $sendmail_path          = $::postfix::params::sendmail_path
  $mastercf               = undef,
) inherits ::postfix::params {

#  notify { "Hale kamo $mysql nebo $postfix_mysql_package": }

  class { '::postfix::install':
    mysql                  => $mysql,
    postfix_package        => $postfix_package,
    postfix_mysql_package  => $postfix_mysql_package,
    postfix_package_ensure => $postfix_package_ensure,
    service_restart        => $service_restart,
  }

  postfix::instance { 'postfix':
    myhostname                           => $myhostname,
    mydomain                             => $mydomain,
    myorigin                             => $myorigin,
    inet_interfaces                      => $inet_interfaces,
    inet_protocols                       => $inet_protocols,
    master_service_disable               => $master_service_disable,
    proxy_interfaces                     => $proxy_interfaces,
    mydestination                        => $mydestination,
    local_recipient_maps                 => $local_recipient_maps,
    luser_relay                          => $luser_relay,
    unknown_local_recipient_reject_code  => $unknown_local_recipient_reject_code,
    mynetworks_style                     => $mynetworks_style,
    mynetworks                           => $mynetworks,
    relay_domains                        => $relay_domains,
    relayhost                            => $relayhost,
    relay_recipient_maps                 => $relay_recipient_maps,
    transport_maps                       => $transport_maps,
    in_flow_delay                        => $in_flow_delay,
    alias_maps                           => $alias_maps,
    alias_database                       => $alias_database,
    recipient_delimiter                  => $recipient_delimiter,
    home_mailbox                         => $home_mailbox,
    mail_spool_directory                 => $mail_spool_directory,
    mailbox_command                      => $mailbox_command,
    smtpd_banner                         => $smtpd_banner,
    setgid_group                         => $setgid_group,
    mailbox_size_limit                   => $mailbox_size_limit,
    message_size_limit                   => $message_size_limit,
    mail_name                            => $mail_name,
    virtual_alias_domains                => $virtual_alias_domains,
    virtual_alias_maps                   => $virtual_alias_maps,
    virtual_mailbox_domains              => $virtual_mailbox_domains,
    virtual_mailbox_maps                 => $virtual_mailbox_maps,
    virtual_mailbox_base                 => $virtual_mailbox_base,
    virtual_uid_maps                     => $virtual_uid_maps,
    virtual_gid_maps                     => $virtual_gid_maps,
    virtual_transport                    => $virtual_transport,
    dovecot_destination                  => $dovecot_destination,
    masquerade_classes                   => $masquerade_classes,
    masquerade_domains                   => $masquerade_domains,
    smtpd_helo_required                  => $smtpd_helo_required,
    smtpd_client_restrictions            => $smtpd_client_restrictions,
    smtpd_helo_restrictions              => $smtpd_helo_restrictions,
    smtpd_sender_restrictions            => $smtpd_sender_restrictions,
    smtpd_recipient_restrictions         => $smtpd_recipient_restrictions,
    smtpd_data_restrictions              => $smtpd_data_restrictions,
    smtpd_end_of_data_restrictions       => $smtpd_end_of_data_restrictions,
    smtpd_delay_reject                   => $smtpd_delay_reject,
    ssl                                  => $ssl,
    smtpd_tls_key_file                   => $smtpd_tls_key_file,
    smtpd_tls_cert_file                  => $smtpd_tls_cert_file,
    smtpd_tls_CAfile                     => $smtpd_tls_CAfile,
    smtpd_sasl_auth                      => $smtpd_sasl_auth,
    smtpd_sasl_type                      => $smtpd_sasl_type,
    smtpd_sasl_path                      => $smtpd_sasl_path,
    smtp_sasl_auth                       => $smtp_sasl_auth,
    smtp_sasl_password_maps              => $smtp_sasl_password_maps,
    smtp_sasl_security_options           => $smtp_sasl_security_options,
    smtp_tls_CAfile                      => $smtp_tls_CAfile,
    smtp_tls_CApath                      => $smtp_tls_CApath,
    smtp_tls_key_file                    => $smtp_tls_key_file,
    smtp_tls_cert_file                   => $smtp_tls_cert_file,
    smtp_tls_security_level              => $smtp_tls_security_level,
    smtp_tls_secure_cert_match           => $smtp_tls_secure_cert_match,
    smtp_tls_note_starttls_offer         => $smtp_tls_note_starttls_offer,
    smtp_tls_mandatory_ciphers           => $smtp_tls_mandatory_ciphers,
    smtpd_tls_ask_ccert                  => $smtpd_tls_ask_ccert,
    tls_append_default_CA                => $tls_append_default_CA,
    smtp_sasl_tls                        => $smtp_sasl_tls,
    smtp_use_tls                         => $smtp_use_tls,
    canonical_maps                       => $canonical_maps,
    sender_canonical_maps                => $sender_canonical_maps,
    smtp_generic_maps                    => $smtp_generic_maps,
    relocated_maps                       => $relocated_maps,
    extra_main_parameters                => $extra_main_parameters,
    smtp_content_filter                  => $smtp_content_filter,
    smtps_content_filter                 => $smtps_content_filter,
    submission                           => $submission,
    submission_smtpd_enforce_tls         => $submission_smtpd_enforce_tls,
    submission_smtpd_tls_security_level  => $submission_smtpd_tls_security_level,
    submission_smtpd_sasl_auth_enable    => $submission_smtpd_sasl_auth_enable,
    smtps_smtpd_sasl_auth_enable         => $smtps_smtpd_sasl_auth_enable,
    submission_smtpd_client_restrictions => $submission_smtpd_client_restrictions,
    smtps_smtpd_client_restrictions      => $smtps_smtpd_client_restrictions,
    master_services                      => $master_services,
    header_checks                        => $header_checks,
    body_checks                          => $body_checks,
    postscreen                           => $postscreen,
    postscreen_access_list               => $postscreen_access_list,
    postscreen_blacklist_action          => $postscreen_blacklist_action,
    postscreen_cache_map                 => $postscreen_cache_map,
    postscreen_greet_wait                => $postscreen_greet_wait,
    postscreen_greet_banner              => $postscreen_greet_banner,
    postscreen_greet_action              => $postscreen_greet_action,
    postscreen_dnsbl_sites               => $postscreen_dnsbl_sites,
    postscreen_dnsbl_reply_map           => $postscreen_dnsbl_reply_map,
    postscreen_dnsbl_threshold           => $postscreen_dnsbl_threshold,
    postscreen_dnsbl_action              => $postscreen_dnsbl_action,
    postgrey                             => $postgrey,
    postgrey_policy_service              => $postgrey_policy_service,
    clamav                               => $clamav,
    command_directory                    => $command_directory,
    config_directory                     => $config_directory,
    daemon_directory                     => $daemon_directory,
    data_directory                       => $data_directory,
    manpage_directory                    => $manpage_directory,
    readme_directory                     => $readme_directory,
    sample_directory                     => $sample_directory,
    postfix_package                      => $postfix_package,
    postfix_package_ensure               => $postfix_package_ensure,
    postgrey_package                     => $postgrey_package,
    service_restart                      => $service_restart,
    root_group                           => $root_group,
    mailq_path                           => $mailq_path,
    newaliases_path                      => $newaliases_path,
    sendmail_path                        => $sendmail_path,
    masterfs                             => $mastercf,
  }

}
